/*
 * DO NOT EDIT THIS FILE. Generated by checkmk.
 * Edit the original source file "test.check" instead.
 */

#include <check.h>
#include <errno.h>
#include <limits.h>
#include <stdio.h>
#include <stdlib.h>

#include "s21_viewer_3d.h"

START_TEST(viewer_1) {
  data_t *obj;
  int error;
  char *filename_str = "Skull.obj";
  obj = obj_point_output(filename_str, &error);
  center(obj);
  adjust(obj, 2);
  rotateX(obj, 2);
  rotateY(obj, -1);
  rotateZ(obj, 0.3);
  moveObj_x(obj, 0.5);
  moveObj_y(obj, 0.5);
  moveObj_z(obj, 0.5);
  scale(obj, 2);
  free_data(obj);
}
END_TEST

START_TEST(viewer_2) {
  data_t *obj;
  int error;
  char *filename_str = "Sku.obj";
  obj = obj_point_output(filename_str, &error);
}
END_TEST

START_TEST(viewer_3) {
  data_t *obj, *obj_2;
  int error;
  char *filename_str = "Skull.obj";
  obj = obj_point_output(filename_str, &error);
  obj_2 = copyData(obj, &error);
  free_data(obj);
  free_data(obj_2);
}
END_TEST

int main(void) {
  Suite *s1 = suite_create("Core");
  TCase *tc1_1 = tcase_create("Core");
  SRunner *sr = srunner_create(s1);
  int nf;

  suite_add_tcase(s1, tc1_1);
  tcase_add_test(tc1_1, viewer_1);
  tcase_add_test(tc1_1, viewer_2);
  tcase_add_test(tc1_1, viewer_3);

  srunner_run_all(sr, CK_ENV);
  nf = srunner_ntests_failed(sr);
  srunner_free(sr);

  return nf == 0 ? 0 : 1;
}
